# Generated by Django 4.2.2 on 2023-12-24 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=300, null=True, unique=True, verbose_name='نام کاربری')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='نام خانوادگی')),
                ('telegram_id', models.CharField(max_length=125, unique=True, verbose_name='شماره تلگرام')),
                ('telegram_username', models.CharField(blank=True, max_length=125, null=True, verbose_name='آیدی تلگرام')),
                ('balance', models.IntegerField(default=0, verbose_name='موجودی')),
                ('mobile', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='تلفن همراه')),
                ('data', models.TextField(default='{}')),
                ('alarm_count', models.IntegerField(default=0, verbose_name='اخطار های دریافتی')),
                ('alarm_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان آخرین اخطار')),
                ('parent', models.CharField(blank=True, max_length=128, null=True, verbose_name='معروف')),
                ('refal', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='کد دعوت')),
                ('refal_income', models.IntegerField(default=0, verbose_name='درآمد')),
                ('refal_count', models.IntegerField(default=0, verbose_name='تعداد زیر مجموعه ها')),
                ('is_mobile_accepted', models.BooleanField(default=False, verbose_name='تلفن همراه تایید شده است ؟')),
                ('save_log', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('recovery', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'حساب کاربری',
                'verbose_name_plural': 'حساب های کاربری',
                'ordering': ('-published',),
                'permissions': (('can_see_admin_page', 'Can see admin page'),),
            },
        ),
        migrations.CreateModel(
            name='IPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='آی پی')),
                ('device', models.CharField(max_length=128, verbose_name='دستگاه')),
                ('browser', models.CharField(max_length=128, verbose_name='مرورگر')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ',
                'verbose_name_plural': 'لاگ ها',
                'ordering': ('-published',),
            },
        ),
    ]
