# Generated by Django 4.2.2 on 2023-12-24 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='نام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=32, verbose_name='کلید')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشور ها',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='نام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(verbose_name='تعداد روز')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='نام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('count', models.FloatField(verbose_name='مقدار گیگ')),
                ('user_count', models.IntegerField(verbose_name='تعداد کاربر')),
                ('price', models.IntegerField(verbose_name='هزینه (تومان)')),
                ('cost', models.IntegerField(verbose_name='هزینه نگه داری (تومان)')),
                ('price_multi_discount', models.IntegerField(verbose_name='درصد تخفیف فروش عمده')),
                ('price_discount', models.IntegerField(verbose_name='درصد تخفیف تمدید ویژه')),
                ('price_normal_discount', models.IntegerField(verbose_name='درصد تخفیف تمدید معمولی')),
                ('price_ip_discount', models.IntegerField(verbose_name='درصد افزایش نرخ تمدید آی پی')),
                ('is_test', models.BooleanField(default=False, verbose_name='سرویس تست')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_model', to='service.country', verbose_name='کشور')),
                ('periods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periods_model', to='service.period', verbose_name='زمان ها')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس ها',
                'ordering': ('-published',),
            },
        ),
    ]
