# Generated by Django 4.2.2 on 2023-12-24 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField(blank=True, null=True, verbose_name='آیدی پیام')),
                ('message', models.TextField(verbose_name='پیام')),
                ('side', models.CharField(choices=[('user', 'کاربر'), ('support', 'پشتیبان')], default='support', max_length=64, verbose_name='ارسال کننده')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ ها',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64, verbose_name='موضوع درخواست')),
                ('request', models.TextField(verbose_name='درخواست')),
                ('status', models.CharField(choices=[('pending', 'خوانده نشده'), ('suspended', 'درحال پیگیری'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته شده')], default='pending', max_length=64, verbose_name='وضعیت')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت ها',
                'ordering': ('-published',),
            },
        ),
    ]
