# Generated by Django 4.2.2 on 2023-12-24 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField(blank=True, null=True, verbose_name='آیدی سرویس دهنده')),
                ('username', models.CharField(max_length=128, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=254, verbose_name='کلمه عبور')),
                ('token', models.TextField(blank=True, null=True, verbose_name='توکن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال یا غیرفعال')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اکانت',
                'verbose_name_plural': 'اکانت ها',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='اشتراک ویژه', max_length=255, verbose_name='نام ربات')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='حال بروزرسانی')),
                ('card_number', models.CharField(max_length=64, verbose_name='شماره کارت واریز')),
                ('wepad_mobile', models.CharField(max_length=64, verbose_name='شماره ویپاد')),
                ('wepad_token', models.CharField(blank=True, max_length=64, null=True, verbose_name='توکن ویپاد')),
                ('wepad_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='کد ورود ویپاد')),
                ('crypto_wallet', models.CharField(blank=True, max_length=128, null=True, verbose_name='آدرس کیف پول ترون')),
                ('tron_price', models.FloatField(default=1, verbose_name='قیمت هر واحد ترون')),
                ('min_deposit', models.IntegerField(default=0, verbose_name='کمترین مقدار واریز')),
                ('max_deposit', models.IntegerField(default=1000000, verbose_name='بیشترین مقدار واریز')),
                ('referral_count', models.IntegerField(default=10, verbose_name='درصد کارمزد بازاریابی')),
                ('validate_card_time', models.IntegerField(default=3, verbose_name='مدت زمان بررسی تراکنش کارت (دقیقه)')),
                ('card_ban_time', models.IntegerField(default=15, verbose_name='مدت عدم واریز کارت (دقیقه)')),
                ('ticket_count', models.IntegerField(default=1, verbose_name='تعداد تیکت های هم زمان')),
                ('card_deposit_time', models.CharField(default='3-3', help_text='مانند : 0-7 (از 0بامداد تا ساعت 7 صبح)', max_length=32, verbose_name='محدودیت ساعت واریز کارت به کارت')),
                ('alarm_time', models.CharField(default='3-3', help_text='مانند : 3-3 (سه روز قبل و بعد)', max_length=32, verbose_name='قانون آلارم اتمام سرویس')),
                ('alarm_value', models.IntegerField(default=30, help_text='درصد', max_length=32, verbose_name='قانون آلارم حجم اتمام سرویس')),
                ('account_test_period', models.IntegerField(default=10, verbose_name='مدت زمان اکانت تست')),
                ('account_test_value', models.IntegerField(default=100, verbose_name='مقدار حجم اکانت تست')),
                ('account_test_limition', models.IntegerField(default=1, verbose_name='تعداد اکانت های تست قابل مجاز')),
                ('ext_service_role', models.CharField(help_text='مانند : 3-3 (سه روز قبل و بعد)', max_length=32, verbose_name='قانون تمدید سرویس')),
            ],
            options={
                'verbose_name': 'تنظیمات کلی',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField(verbose_name='آیدی سرویس دهنده')),
                ('name', models.CharField(max_length=64, verbose_name='نام')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('address', models.URLField(verbose_name='آدرس پنل')),
                ('username', models.CharField(max_length=6128, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=6128, verbose_name='کلمه عبور')),
                ('token', models.TextField(blank=True, null=True, verbose_name='توکن')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_country', to='service.country', verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'سرور',
                'verbose_name_plural': 'سرور ها',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.IntegerField(verbose_name='آیدی سرویس دهنده')),
                ('name', models.CharField(max_length=64, verbose_name='نام')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, max_length=254, null=True, verbose_name='آدرس کانکشن')),
                ('domain', models.CharField(blank=True, max_length=128, null=True, verbose_name='دامنه')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='پورت')),
                ('type', models.CharField(blank=True, max_length=64, null=True, verbose_name='نوع')),
                ('max_value', models.IntegerField(default=200, verbose_name='حداکثر مقدار حجم')),
                ('locked_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ قفل شدن')),
                ('is_test', models.BooleanField(default=False, verbose_name='آیا نود اکانت تست است ؟')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configure.server', verbose_name='سرور')),
            ],
            options={
                'verbose_name': 'نود',
                'verbose_name_plural': 'نود ها',
                'ordering': ('-published',),
            },
        ),
    ]
