# Generated by Django 4.2.2 on 2023-12-26 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='configure.server', verbose_name='سرور'),
        ),
    ]
