# Generated by Django 4.2.2 on 2023-12-27 00:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0002_alter_node_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='join_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None, verbose_name='کانال های ادد اجباری'),
        ),
    ]
