# Generated by Django 4.2.2 on 2023-12-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0003_siteconfiguration_join_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='join_channels',
            field=models.TextField(blank=True, null=True, verbose_name='کانال های ادد اجباری'),
        ),
    ]
