# Generated by Django 4.2.2 on 2024-01-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configure', '0004_alter_siteconfiguration_join_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='admins_TIDS',
            field=models.TextField(blank=True, null=True, verbose_name='تلگرام آیدی ادمین ها'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='supports_TIDS',
            field=models.TextField(blank=True, null=True, verbose_name='تلگرام آیدی پشتیبان ها'),
        ),
    ]
