# Generated by Django 4.2.2 on 2023-12-24 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jalali_date.admin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='حجم (GB)')),
                ('day', models.IntegerField(verbose_name='مدت زمان (روز)')),
                ('is_lunched', models.BooleanField(default=False, verbose_name='اجرا شده است ؟')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('accounts', models.ManyToManyField(blank=True, null=True, to='configure.account', verbose_name='کانفیگ ها ساخته شده')),
                ('emergency_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configure.node', verbose_name='نود سرور جایگزین')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_server', to='configure.server', verbose_name='سرور مبدا')),
            ],
            options={
                'verbose_name': 'کانفیگ اضطراری',
                'verbose_name_plural': 'کانفیگ های اضطراری',
                'ordering': ('-id',),
            },
            bases=(jalali_date.admin.ModelAdminJalaliMixin, models.Model),
        ),
    ]
