# Generated by Django 4.2.2 on 2023-12-24 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='تومان', verbose_name='مبلغ')),
                ('track_id', models.TextField(blank=True, null=True, verbose_name='کد رهگیری')),
                ('card_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='شماره حساب')),
                ('type', models.CharField(choices=[('cost', 'هزینه'), ('order', 'سفارش'), ('wallet', 'کیف پول'), ('referral', 'بازاریابی'), ('crypto', 'رمز ارز'), ('card', 'کارت به کارت')], default='wallet', max_length=64, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('pending', 'درانتظار پرداخت'), ('payed', 'پرداخت شده'), ('canceled', 'کنسل شده'), ('suspended', 'معلق')], default='pending', max_length=32, verbose_name='وضعیت')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنشات',
                'ordering': ('-published',),
            },
        ),
    ]
