# Generated by Django 4.2.2 on 2023-12-24 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        ('configure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('all_user', models.BooleanField(default=False, verbose_name='یا پیام همگانی باشد ؟')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('country', models.ManyToManyField(blank=True, null=True, to='service.country', verbose_name='کشور ها')),
                ('server', models.ManyToManyField(blank=True, null=True, to='configure.server', verbose_name='سرور ها')),
                ('service', models.ManyToManyField(blank=True, help_text='در صورت اینکه می خواهید به کاربر یک سرویس پیام ارسال کنید سرویس مورد نظر خود را انتخاب نمایید', null=True, to='service.service', verbose_name='سرویس ها')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
                'ordering': ('-id',),
            },
        ),
    ]
