# Generated by Django 4.2.2 on 2023-12-24 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configure', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='کد تخفیف')),
                ('count', models.IntegerField(default=1, verbose_name='تعداد')),
                ('amount', models.FloatField(default=1, verbose_name='درصد')),
                ('expired', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انفضا')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کد های تخفیف',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='هزینه')),
                ('up', models.FloatField(default=0, verbose_name='آپلود')),
                ('down', models.FloatField(default=0, verbose_name='دانلود')),
                ('total', models.FloatField(default=0, verbose_name='کل مصرفی')),
                ('settings', models.TextField(blank=True, null=True, verbose_name='تنظیمات')),
                ('config', models.TextField(blank=True, null=True, verbose_name='کانفیگ اتصال')),
                ('provider_id', models.IntegerField(blank=True, editable=False, null=True, verbose_name='آیدی پنل')),
                ('expired_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('enable', models.BooleanField(default=False, verbose_name='فعال یا غیرفعال')),
                ('alarm_send_data', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال آلارم')),
                ('is_test_config', models.BooleanField(default=False, verbose_name='آیا کانفیگ تست می باشد ؟')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configure.account', verbose_name='اکانت کانفیگ')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.discount', verbose_name='کد تخفیف')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_node_model', to='configure.node', verbose_name='نود کانفیگ')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service', verbose_name='سرویس')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ('-published',),
            },
        ),
        migrations.CreateModel(
            name='ValueMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download', models.FloatField(verbose_name='دانلود')),
                ('upload', models.FloatField(verbose_name='آپلود')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'گزارش مصرف حجم',
                'verbose_name_plural': 'مانیتورینگ مصرف حجم',
                'ordering': ('-published',),
            },
        ),
    ]
