# Generated by Django 4.2.2 on 2023-12-24 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='discount',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, to='service.country', verbose_name='کشور ها'),
        ),
        migrations.AddField(
            model_name='discount',
            name='service',
            field=models.ManyToManyField(blank=True, help_text='در صورت اینکه می خواهید به کاربر یک سرویس پیام ارسال کنید سرویس مورد نظر خود را انتخاب نمایید', null=True, to='service.service', verbose_name='سرویس ها'),
        ),
        migrations.AddField(
            model_name='discount',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='در صورت انتخاب هیچ یک از کاربر ها یا سرویس ها پیام همگانی تلقی می شود.', null=True, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ها'),
        ),
    ]
