# Generated by Django 4.2.2 on 2024-01-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_pass',
            field=models.CharField(default='', max_length=10, verbose_name='یوزرنیم'),
        ),
    ]
