# Stages
START_ROUTES = 2
SERVICE_ROUTES = 2
ACCOUNT_ROUTES = 2
DEPOSIT_ROUTES = 3
DEPOSIT_CARD_ROUTES = 4
DEPOSIT_CRYPTO_ROUTES = 5
DEPOSIT_VALIDATION_ROUTES = 6
DIRECT_PAY_ROUTES = 7
TICKET_ROUTES = 8
DEPOSIT_CARD_VALIDATION_ROUTES = 9
DISCOUNT_ROUTS = 10
SEARCH_SERVICES_ROUTES = 11
REPLY_TICKET_ROUTES = 12